/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const start: () => void;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue__core_9b3796e30d99ddb7___result__Result_____wasm_bindgen_13b433f95525a7fc___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___js_sys_d729b82598a757eb___Array__web_sys_dffc55f4b3f00960___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue______true__1_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue______true__4: (a: number, b: number, c: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue______true__5: (a: number, b: number, c: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue______true__6: (a: number, b: number, c: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue______true__7: (a: number, b: number, c: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue______true__8: (a: number, b: number, c: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue______true__9: (a: number, b: number, c: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___wasm_bindgen_13b433f95525a7fc___JsValue______true__10: (a: number, b: number, c: any) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke___core_9b3796e30d99ddb7___option__Option_web_sys_dffc55f4b3f00960___features__gen_Blob__Blob_______true_: (a: number, b: number, c: number) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_13b433f95525a7fc___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
